### ISSUE TITLE
KeyError: 0 when a digit is not a list index, but a key

### ISSUE THREAD

**Issue by alita91** [pawelzny/dotty_dict#55]
Hello @Dysproz 

Today I found an issue while testing another scenario, could you please check what could be wrong:

```
from dotty_dict import dotty

dot = dotty({'0': {'key': 'value'}})
print(dot['0'])
```
```
Traceback (most recent call last):
  File "z.py", line 8, in <module>
    print(dot['0'])
  File "/usr/local/lib/python3.7/dist-packages/dotty_dict/dotty_dict.py", line 139, in __getitem__
    return get_from(self._split(item), self._data)
  File "/usr/local/lib/python3.7/dist-packages/dotty_dict/dotty_dict.py", line 131, in get_from
    data = data[it]
KeyError: 0
```
Thank you

**Comment by Dysproz** [comment]
Hi @alita91,
I see that you really actively test Dotty ;).
I checked and I think that this bug is related to Bug #50.
Fix for this bug is already merged to master, but it's not yet published to PyPI.
I checked it on my setup and it seems that fix for Bug #50 resolves your problem.
Can you please install dotty from master and check whether you still get this error?
```
pip install git+git://github.com/pawelzny/dotty_dict.git@5c14a706d8c928fb389dd0d2e52baeccd0780de6

```

**Comment by Dysproz** [comment]
@alita91 any update on this bug? Does it work properly for you now?

**Comment by Dysproz** [comment]
Closing this bug as fix is in master branch for a long time
